[Ftr]: limit bytes pool object size
dubbogo/gost pull request #70
Opened 2021-09-11 13:21 UTC by AlexStocks

**What this PR does**:

1 放入 bytes pool 中的 buf 的 size 在 [1kiB, 20kiB] 之间，防止因为过小导致内存碎片过多，也防止过大内存被缓存导致系统内存使用紧张；
2 限制缓存对象数目，防止内存缓存过多导致内存使用紧张

2021-09-11 13:24 UTC, cjphaha commented on bytes/bytes_buffer_pool.go
> +	uatomic "go.uber.org/atomic"
第三方库放在第二个 import 块比较好

2021-09-11 13:29 UTC, cjphaha approved these changes

2021-09-11 13:38 UTC, Mulavar approved these changes

2021-09-12 03:25 UTC, flycash requested changes
Be careful about the race-condition

2021-09-12 03:25 UTC, flycash commented on bytes/bytes_buffer_pool.go
> +	}
```go
        bufCap := buf.Cap()
	if bufCap < minBufCap || bufCap > maxBufCap {
		return
	}
       poolObjectNumber.Add(1)
       if poolObjectNumber.Load() > maxPoolObjectNum {
                poolObjectNumber.Add(-1)
		return
	}
       defaultPool.Put(buf)
```

2021-09-12 05:03 UTC, AlexStocks commented on bytes/bytes_buffer_pool.go
> +	}
如果说边界条件，这里边界条件多了去了，譬如如果有多个 PutBytesBuffer 被并行执行的时候，这里还有很多需要注意的地方。但是，这里仅仅需要控制大概准确就可以了，没必要精确。

2021-09-12 07:54 UTC, merged

2021-09-12 09:24 UTC, wongoo commented
1. bytes.Buffer 会自己增长，是不是可以不用限制最小值吗？
2. sync.Pool 会将对象进行垃圾回收，是不是就不用限制pool的大小了？